// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQMGPoneVZgVgQsh4vx3Q-JXFcC7X2g4Q',
    appId: '1:691966658691:web:8f043e76f548f5378b73b6',
    messagingSenderId: '691966658691',
    projectId: 'crud-1303b',
    authDomain: 'crud-1303b.firebaseapp.com',
    storageBucket: 'crud-1303b.appspot.com',
    measurementId: 'G-V1TFKKLB9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVHQWw2-p6gXeQtFUTegez6gXOflGz4zw',
    appId: '1:691966658691:android:d2a2c006623e41d08b73b6',
    messagingSenderId: '691966658691',
    projectId: 'crud-1303b',
    storageBucket: 'crud-1303b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANoDGJG5j-NWAww2ev2G_MG2AGIMWJ_lk',
    appId: '1:691966658691:ios:6afbb69fc20a46138b73b6',
    messagingSenderId: '691966658691',
    projectId: 'crud-1303b',
    storageBucket: 'crud-1303b.appspot.com',
    iosClientId: '691966658691-ag0kjbm660fampnabqhagc33a0j4c0ba.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudProject',
  );
}
